namespace kDriveApiWrapper.Models
{
    /// <summary>
    /// The file category.
    /// </summary>
    public partial class FileCategory : Data
    {
        /// <summary>
        /// Category identifier
        /// </summary>

        [JsonPropertyName("category_id")]
        public int Category_id { get; set; } = default!;

        /// <summary>
        /// Time when the category was added to file
        /// </summary>

        [JsonPropertyName("added_at")]
        public int Added_at { get; set; } = default!;

        /// <summary>
        /// State of user validation after auto assignment from AI.
        /// </summary>

        [JsonPropertyName("user_validation")]
        [JsonConverter(typeof(JsonStringEnumConverter))]
        public FileCategoryUser_validation? User_validation { get; set; } = default!;

        /// <summary>
        /// Whether the Category was generated by an AI or not
        /// </summary>

        [JsonPropertyName("is_generated_by_ai")]
        public bool Is_generated_by_ai { get; set; } = default!;

        /// <summary>
        /// User identifier
        /// </summary>

        [JsonPropertyName("user_id")]
        public int? User_id { get; set; } = default!;

        /// <summary>
        /// Gets or sets the category.
        /// </summary>
        [JsonPropertyName("category")]
        public Category Category { get; set; } = default!;
    }
}